version: 2
sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez data sourcee
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez
        columns:
          - name: product_id
            description: is it product_id
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
      - name: ship
        identifier: raw_gz_ship
        
      - name: product
        identifier: raw_gz_product
        description: product of greenweez
        columns: 
          - name: products_id
            description: its primary key
            tests:
              - unique
              - not_null
      - name: adwords
        identifier: raw_gz_adwords
      - name: bing
        identifier: raw_gz_bing
      - name: criteo 
        identifier: raw_gz_criteo
      - name: facebook
        identifier: raw_gz_facebook
      

              
                  
                  